services:
  db:
    image: mariadb:latest
    container_name: booking-classroom
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: booking_classroom
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
